### ISSUE TITLE
How should PHP be configured to start together with Apache?

### ISSUE THREAD

**Issue by 1825679767** [CraftedRO/Jeutie-s-Server-Control#2]
How should PHP be configured to start together with Apache?

**Comment by CraftedRO** [comment]
According to gemini something like this:
To configure PHP to start together with Apache, you'll need to make some changes to your Apache configuration file (usually httpd.conf). Here's a breakdown of the steps involved:

1. Load the PHP module:

Add the following line to your httpd.conf file, typically located in your Apache installation directory:
Apache
LoadModule php_module "path/to/php/modules/php_module.so"

Replace "path/to/php/modules/php_module.so" with the actual path to your PHP module file. This file should be named php_module.so and located within the modules directory of your PHP installation.
2. Add PHP handler:

To associate PHP files with the PHP module, you'll need to add a handler. This handler will tell Apache to process PHP files using the PHP module. Add the following line to your httpd.conf file:
Apache
AddHandler php-script .php

3. Set the PHP executable path:

If you haven't already set the PHP executable path, you can do so using the following line:
Apache
PHPIniDir "path/to/php.ini"

Replace "path/to/php.ini" with the actual path to your PHP configuration file.
4. Restart Apache:

After making these changes, save the httpd.conf file and restart Apache. This will ensure that the new configuration takes effect.
Additional considerations:

PHP installation: Make sure you have PHP installed on your system and that the module files are accessible to Apache.
File permissions: Ensure that Apache has the necessary permissions to read and execute PHP files.
PHP configuration: You may need to modify the PHP configuration file (php.ini) to suit your specific needs.
By following these steps, you should be able to successfully configure PHP to start together with Apache, allowing you to run PHP applications on your web server.
